### ISSUE TITLE
Bug: Data sporadically not showing up in query

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#17]
In the past day or so the query section has been sporadically not showing the data. Not sure how to replicate the issue, but will post picture below that shows like I have no data uploaded, when in reality I do.

![image](https://user-images.githubusercontent.com/1574010/80173303-3d6e7000-85a4-11ea-8af0-3f15142af5ed.png)

**Comment by sgalizia** [comment]
refreshing the page does not fix the issue either

**Comment by andythorne** [comment]
Hi Sam, happy Friday! This seems to have been caused by a change I did to how the platform imports new TSM data in order to facilitate processing large import files.

Looooong story short-ish - when a new TSM log is uploaded, all weekly and daily reports are regenerated for the time period the import covers. The report generation happens _after_ the import, in the background. It's not communicated on the UI that this is happening at all atm. Whilst the new reports are being generated, it clears all old reports, so there's a period of time where the old reports have been deleted and the new reports have not yet been generated, which causes no data to display on in the UI. I think this is the root of this issue.

The good news is that generating a report for a day takes < 1 sec and a week < 5 secs, so I'll make a change that only deletes reports when a new report is requested _for a given date_, which should reduce the chance of seeing no data at all. I'll also add in a "this report is being re-generated" to the UI so you know that the data will change!

Thanks for the report again! Please keep them coming!

**Comment by sgalizia** [comment]
Thanks for the detailed response! Really loving the changes, keep them coming!

**Comment by andythorne** [comment]
I've just released an update for this! The time to generate imports has been decreased and a yellow spinner and tooltip if the report is currently being generated!
![image](https://user-images.githubusercontent.com/1301181/80237643-fbe9cd80-8654-11ea-9a9e-c66745f39e3b.png)
