### ISSUE TITLE
Bug: Bars appear to be offcenter in the bar graphs

### ISSUE THREAD

**Issue by sgalizia** [andythorne/magurokun-issues#24]
Title pretty much says it all, picture to follow:

![image](https://user-images.githubusercontent.com/1574010/80856152-34ad1800-8bfc-11ea-8192-3850a03d8ef6.png)

**Comment by andythorne** [comment]
Hi Sam! This is because you've tracked multiple items on an "unstacked" bar chart. On a bar chart, you can either show the data "stacked", where each value is added on top of the previous value, or not-stacked, where every item will have it's own bar. When it's not-stacked, the bars are shown side-by-side for each day:

Not stacked:
![image](https://user-images.githubusercontent.com/1301181/80865318-6ebffd80-8c80-11ea-8650-cc2fd773f530.png)

Stacked:
![image](https://user-images.githubusercontent.com/1301181/80865323-7d0e1980-8c80-11ea-9a7d-b010d2ab5239.png)

Hope that helps!

**Comment by sgalizia** [comment]
Ah yes, that makes sense! Sorry, not a bug after all haha
